INSERT INTO guests (full_name, group_id, response) VALUES
('John Doe', 1, 'yes'),
('Jane Doe', 1, 'yes'),
('Alice Johnson', 2, 'no'),
('Robert Brown', 2, 'yes'),
('Emily Davis', 3, 'yes'),
('Michael Doe', 3, 'no'),
('Jessica Wilson', 4, 'yes'),
('Daniel Moore', 4, 'yes'),
('Laura Taylor', 5, 'no'),
('David Anderson', 5, 'yes'),
('Sarah Thomas', 6, 'yes'),
('James Jackson', 6, 'no'),
('Linda White', 7, 'yes'),
('Paul Harris', 7, 'yes'),
('Karen Martin', 8, 'no'),
('Mark Thompson', 8, 'yes'),
('Nancy Garcia', 9, 'yes'),
('Kevin Martinez', 9, 'no'),
('Sandra Robinson', 10, 'yes'),
('Charles Clark', 10, 'yes'),
('Mary Rodriguez', 11, 'no response'),
('Steven Lewis', 11, 'yes'),
('Patricia Lee', 12, 'yes'),
('Thomas Walker', 12, 'no'),
('Barbara Hall', 13, 'yes'),
('Larry Allen', 13, 'no response'),
('Brenda Young', 14, 'yes'),
('Frank King', 14, 'no'),
('Catherine Wright', 15, 'no response'),
('Gary Lopez', 15, 'yes'),
('Megan Hill', 16, 'no'),
('Justin Scott', 16, 'yes'),
('Rebecca Green', 17, 'no response'),
('Brian Adams', 17, 'yes'),
('Angela Baker', 18, 'no'),
('Ryan Gonzalez', 18, 'yes'),
('Carol Nelson', 19, 'no response'),
('Eric Carter', 19, 'yes'),
('Diana Mitchell', 20, 'no'),
('Jerry Perez', 20, 'yes'),
('Stephanie Roberts', 21, 'no response'),
('Joe Turner', 21, 'yes'),
('Kelly Phillips', 22, 'no'),
('Ray Campbell', 22, 'yes'),
('Ruth Parker', 23, 'no response'),
('Ethan Evans', 23, 'yes'),
('Betty Edwards', 24, 'no'),
('Scott Collins', 24, 'yes'),
('Judy Stewart', 25, 'no response'),
('Bruce Sanchez', 26, 'yes');
