INSERT INTO guests (first_name, last_name, response)
VALUES
    ('John', 'Doe', 'no response'),
    ('Jane', 'Doe', 'no response'),
    ('Jane', 'Smith', 'no response'),
    ('Michael', 'Johnson', 'no response'),
    ('Emily', 'Williams', 'no response'),
    ('Daniel', 'Brown', 'no response'),
    ('Sarah', 'Jones', 'no response'),
    ('Christopher', 'Davis', 'no response'),
    ('Jessica', 'Miller', 'no response'),
    ('Matthew', 'Wilson', 'no response'),
    ('Jennifer', 'Moore', 'no response'),
    ('Andrew', 'Taylor', 'no response'),
    ('Elizabeth', 'Anderson', 'no response'),
    ('David', 'Thomas', 'no response'),
    ('Laura', 'Jackson', 'no response'),
    ('James', 'White', 'no response'),
    ('Amanda', 'Martin', 'no response'),
    ('Ryan', 'Thompson', 'no response'),
    ('Stephanie', 'Garcia', 'no response'),
    ('Kevin', 'Martinez', 'no response'),
    ('Melissa', 'Robinson', 'no response');
